#
# default job configuration 
#
# Note: this is a YAML file, indentation is important, TAB characters are not permitted.
#     You must use an exact number of spaces to denote each indentation level.
#     This file uses 4 space characters for each level.
#

default.properties:
    executor: RuntimeExec
    java_flags: -Xmx512m -Dhttp.proxyHost=<http.proxyHost> -Dhttp.proxyPort=<http.proxyPort>
    # flag to allow users to input arbitrary network file paths as value to input file input parameters
    #allow.input.file.paths: false
    # flag to enable batch execution of jobs from the run module web page
    allow.batch.process: false
    # flag to allow users to submit jobs, set this to false to prevent new jobs
    allow.new.job: true

    # the max number of files to display in uploaded files tab
    upload.maxfiles: 50
    upload.partition.size: 10000000
    upload.max.size: 20000000000
    upload.jumploader: true
    upload.purge.all: false
    # flag to disable listing uploaded input files in the menu
    upload.display.dirs: true
    
    # flag to disable listing file size and modification date in the gui, 
    display.file.info: true
    
    # location for user data
    user.root.dir: "../users"
    # by default each gp user account gets a home directory in <user.root.dir>/<user.id>
    
    # location for user files uploaded directly to the server from the upload tab
    # by default, files are uploaded to each user's uploads directory, <user.root.dir>/<user.id>/uploads

    # Turn off input file displays
    display.input.results: false

    # for the file downloader, set the max file size (in bytes) to display inline in the web browser
    max.inline.size: 10000000
    
    # for 'Create Pipeline', the max file size (in bytes) to copy when creating a new pipeline
    # (default=250mB)
    pipeline.max.file.size: 256000000
    
    genomeSpaceEnabled: false
    genomeSpaceUrl: https://identity.genomespace.org:8444/identityServer/xrd.jsp
    genomeSpaceEnvironment: prod
    
    # 
    # for per-module End-user license agreements (EULA)
    #
    # set this to true, to enable the EulaManager
    org.genepattern.server.eula.EulaManager.enabled: true
    # set the list of 0 or more remoteUrls for recording each EULA
    # this is the default value, so it's not necessary to set
    #org.genepattern.server.eula.EulaManager.remoteUrl: "http://eulas.genepattern.org/eulas"
    # an empty list means, don't POST
    #org.genepattern.server.eula.EulaManager.remoteUrl: []
    
    #
    # for experimental features with pipeline execution
    #
    org.genepattern.server.executor.pipeline.parallelExec: false


executors:
    # default executor for all jobs, it is included in GenePattern
    RuntimeExec:
        classname: org.genepattern.server.executor.RuntimeCommandExecutor
        configuration.properties:
            # the total number of jobs to run concurrently
            num.threads: 20
