#
# default job configuration 
#
# Note: this is a YAML file, indentation is important, TAB characters are not permitted.
#     You must use an exact number of spaces to denote each indentation level.
#     This file uses 4 space characters for each level.
#

default.properties:
    executor: LocalJobRunner
    java_flags: -Xmx512m -Dhttp.proxyHost=<http.proxyHost> -Dhttp.proxyPort=<http.proxyPort>
    # flag to allow users to input arbitrary network file paths as value to input file input parameters
    #allow.input.file.paths: false
    
    # filter job results based on the given comma separated list of glob patterns
    # default setting hides all files which begin with a '.' character
    job.FilenameFilter: [ ".*" ]
    
    # flag to enable batch execution of jobs from the run module web page
    allow.batch.process: false
    # flag to allow users to submit jobs, set this to false to prevent new jobs
    allow.new.job: true

    # the max number of files to display in uploaded files tab
    upload.maxfiles: 50
    upload.partition.size: 10000000
    upload.max.size: 20000000000
    upload.jumploader: true
    # rules for the file purger for purging files from each user's uploads tab 
    #     using the same schedule as the job purger, it only purges files older than the cutoff date
    # when purge.all is true, it means purge all files (default: false)
    upload.purge.all: false 
    # when purge.tmp is true, it means purge the tmp files (default: true)
    upload.purge.tmp: true
    # when purge.partial is true, it means purge any (presumably) stalled partially uploaded files
    upload.purge.partial: true
    # rule for hiding/showing the tmp.dir in the uploads tab, by default it's hidden
    upload.hide.tmp: true
    
    # flag to disable listing file size and modification date in the gui, 
    display.file.info: true
    
    # by default each gp user account gets a home directory in <GenePatternServer>/users/<user.id>
    # Set the 'user.root.dir' property to customize this, e.g.
    # user.root.dir: /Applications/GenePatternServer/users
    
    # location for user files uploaded directly to the server from the upload tab
    # by default, files are uploaded to each user's uploads directory, <user.root.dir>/<user.id>/uploads

    # Turn off input file displays
    display.input.results: false

    # for the file downloader, set the max file size (in bytes) to display inline in the web browser
    max.inline.size: 10000000
    
    # for 'Create Pipeline', the max file size (in bytes) to copy when creating a new pipeline
    # (default=250mB)
    pipeline.max.file.size: 256000000
    
    #
    # GenomeSpace integration
    #
    genomeSpaceEnabled: true
    genomeSpaceUrl: https://identity.genomespace.org/identityServer/xrd.jsp
    genomeSpaceEnvironment: prod

    #
    # GPARC integration
    #
    gparcUploadURL: http://www.gparc.org/server_upload.php
    gparcSubmitURL: http://www.gparc.org/uniqid

    #
    # Google Analytics, available in 3.9.2+
    #
    #googleAnalytics.enabled: true
    #googleAnalytics.trackingId: ""
    
    # 
    # for per-module End-user license agreements (EULA)
    #
    # set this to true, to enable the EulaManager
    org.genepattern.server.eula.EulaManager.enabled: true
    # set the list of 0 or more remoteUrls for recording each EULA
    # this is the default value, so it's not necessary to set
    #org.genepattern.server.eula.EulaManager.remoteUrl: "http://eulas.genepattern.org/eulas"
    # an empty list means, don't POST
    #org.genepattern.server.eula.EulaManager.remoteUrl: []
    
    #
    # by default run pipeline steps in parallel
    # Set this to 'false' to revert back to the GP <=3.7.0 behavior
    #
    org.genepattern.server.executor.pipeline.parallelExec: true

    #
    # Settings for the 'Modules & Pipelines' panel
    #
    # By default, all categories are shown, to  hide a category add it to the list of hiddenCategories
    # (feature added in 3.7.3)
    org.genepattern.server.cm.CategoryManager.hiddenCategories: [ ]
    #
    # Check the GP database for custom categories.  
    # To get the list of custom categories ...  go to the /gp/sql.jsp page
    #     select * from task_category
    # To add a custom category, use the base lsid of the module
    #     insert into task_category (task_category) values ('<baseLsid>', '<categoryName>')
    # (added in 3.7.3)
    org.genepattern.server.cm.CategoryManager.checkCustomCategories: true
    
executors:
    # default executor for all jobs, it is included in GenePattern
    # switched from RuntimeExec to LocalJobRunner in 3.9.0
    LocalJobRunner:
        classname: org.genepattern.server.executor.drm.JobExecutor
        configuration.properties:
            jobRunnerClassname: org.genepattern.drm.impl.local.commons_exec.LocalCommonsExecJobRunner
            jobRunnerName: CommonsExecJobRunner
            # interval for polling for job status (in ms)
            #minDelay: 100
            ## when 'useDynamicDelay' is true, use a built-in algorithm to increase the polling interval
            #useDynamicDelay: true
            ## the max polling interval, when 'useDynamicDelay' is true
            #maxDelay: 30000
            
        default.properties:
            # name of hidden log file added to each job result directory
            job.logFile: ".rte.out"
            